proxmox:
  enabled: False
  server_ip: ""
  username: "root@pam"
  password: ""
  verify_ssl: False
  node: ""

temperature:
  limit: 50  # Temperature limit in degrees Celsius

web:
  port: 5050

thingspeak:
  enabled: True
  temp_channel_id: "2737753"